"""init

Revision ID: a27a6902544b
Revises: 
Create Date: 2026-05-25 15:52:01.066268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'a27a6902544b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_chunks',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('file_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('kb_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_chunks_file_id'), 'kb_chunks', ['file_id'], unique=False)
    op.create_index(op.f('ix_kb_chunks_kb_id'), 'kb_chunks', ['kb_id'], unique=False)
    op.create_table('kb_file_records',
    sa.Column('file_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('parsed_text', sa.Text(), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('parse_task_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_table('kb_members',
    sa.Column('kb_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('kb_id', 'user_id')
    )
    op.create_table('kb_nodes',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('kb_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('node_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('parent_path', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('full_path', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('oss_key', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('oss_url', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_nodes_kb_id'), 'kb_nodes', ['kb_id'], unique=False)
    op.create_table('knowledge_bases',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permission', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('share_token', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    op.create_table('parse_tasks',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('kb_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parse_tasks_kb_id'), 'parse_tasks', ['kb_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_parse_tasks_kb_id'), table_name='parse_tasks')
    op.drop_table('parse_tasks')
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('knowledge_bases')
    op.drop_index(op.f('ix_kb_nodes_kb_id'), table_name='kb_nodes')
    op.drop_table('kb_nodes')
    op.drop_table('kb_members')
    op.drop_table('kb_file_records')
    op.drop_index(op.f('ix_kb_chunks_kb_id'), table_name='kb_chunks')
    op.drop_index(op.f('ix_kb_chunks_file_id'), table_name='kb_chunks')
    op.drop_table('kb_chunks')
    # ### end Alembic commands ###
